
/**************************************************************
 *	
 *	blue_danube, 8 bit, 8000Hz,
 *	1 channel, 661500 bytes/channel
 *	Total Size: 1 * 661500 + 4 (header) = 661544 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Philip Mallory\Desktop\wav2c\blue_danube.wav
 *	Time-stamp: Fri Dec 09 02:57:16 2011
 *	
 **************************************************************/

#ifndef __BLUE_DANUBEH__
#define __BLUE_DANUBEH__

#define BLUE_DANUBEFREQ 8000
#define BLUE_DANUBELEN 661500

extern const unsigned char blue_danube[661500];

#endif /* __BLUE_DANUBEH__ */
